INSERT INTO DEPARTMENT (DEP_ID, DEP_NAME)
VALUES ('20', '資訊部'),
       ('30', '管理部'),
       ('40', '財務部');

INSERT INTO EMPLOYEE (NAME, DEP_ID, GENDER, PHONE, ADDRESS, AGE, CREATDATE, MODIFYDATE)
VALUES ('林OO', 20, 'm', '0900000000', '深海的大鳳梨一號二樓', 26, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
	   ('陳OO', 30, 'f', '0900000000', '深海的大鳳梨一號二樓', 30, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());