DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE
(
	EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	DEP_ID INT NOT NULL,
	GENDER VARCHAR(2) DEFAULT NULL,
	PHONE VARCHAR(255) NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	AGE INT NOT NULL,
	CREATDATE TIMESTAMP NOT NULL,
	MODIFYDATE TIMESTAMP NOT NULL
);

CREATE TABLE DEPARTMENT
(
	DEP_ID INT PRIMARY KEY,
	DEP_NAME VARCHAR(200) NOT NULL
);